const accessGate=document.querySelector('[data-access-gate]'),accessForm=document.querySelector('[data-access-form]'),accessError=document.querySelector('[data-access-error]');
function unlockPreview(){document.body.classList.remove('locked');accessGate.classList.add('is-leaving');setTimeout(()=>{accessGate.hidden=true},650)}
if(sessionStorage.getItem('ametist-preview-access')==='granted'){accessGate.hidden=true;document.body.classList.remove('locked')}else{accessForm.addEventListener('submit',event=>{event.preventDefault();const password=new FormData(accessForm).get('password');if(password==='9876'){sessionStorage.setItem('ametist-preview-access','granted');unlockPreview()}else{accessError.hidden=false;accessGate.classList.remove('shake');void accessGate.offsetWidth;accessGate.classList.add('shake');accessForm.elements.password.select()}})}
const doctors=[['Бабин','Вячеслав Вячеславович','Терапевт, кардиолог, аритмолог','Кандидат медицинских наук','therapy'],['Бабина','Ирина Александровна','Ревматолог, терапевт, врач УЗИ','Функциональная диагностика','therapy'],['Калинина','Екатерина Николаевна','Терапевт','','therapy'],['Закройщикова','Инесса Владимировна','Невролог','Кандидат медицинских наук','neuro'],['Ганин','Дмитрий Алексеевич','Невролог','','neuro'],['Свиридонова','Марина Александровна','Эндокринолог, диетолог','Кандидат медицинских наук','therapy'],['Куренков','Андрей Владимирович','Педиатр','','children'],['Харзиани','Елена Валерьевна','Клинический психолог','','psychology'],['Мавлиева','Радмила Руслановна','Психолог','','psychology'],['Кузнецов','Павел Андреевич','Акушер-гинеколог','Кандидат медицинских наук','women'],['Голубкова','Наталья Сергеевна','Акушер-гинеколог, гинеколог-эндокринолог, врач УЗИ','','women'],['Павличенко','Светлана Николаевна','Терапевт, кардиолог, диетолог','Клинический фармаколог, к. м. н.','therapy'],['Кузина','Дарья Евгеньевна','Детский гастроэнтеролог','','children'],['Исакова','Светлана Сергеевна','Терапевт, гастроэнтеролог','','therapy']];
const grid=document.querySelector('[data-doctor-grid]'),more=document.querySelector('[data-doctor-more]');
function render(filter='all',expanded=false){const list=doctors.filter(d=>filter==='all'||d[4]===filter);grid.innerHTML=list.map((d,i)=>`<article class="doctor ${!expanded&&i>7?'hidden':''}"><div class="doctor-portrait"><span class="doctor-initials">${d[0][0]}${d[1][0]}</span></div><div class="doctor-info"><h3>${d[0]}<br>${d[1]}</h3><p>${d[2]}</p><small>${d[3]||'Специалист клиники «Аметист»'}</small><button class="js-book">Записаться ↗</button></div></article>`).join('');more.hidden=list.length<=8;bindBooking()}
render();
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');button.classList.add('active');render(button.dataset.filter)}));
more.addEventListener('click',()=>{document.querySelectorAll('.doctor.hidden').forEach(card=>card.classList.remove('hidden'));more.hidden=true});
const menuButton=document.querySelector('.menu-btn'),menu=document.querySelector('#menu');menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));menu.classList.toggle('open')});menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const modal=document.querySelector('.modal');function bindBooking(){document.querySelectorAll('.js-book').forEach(button=>button.onclick=()=>modal.showModal())}bindBooking();document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});modal.querySelector('form').addEventListener('submit',event=>{event.preventDefault();event.currentTarget.hidden=true;modal.querySelector('.success').hidden=false});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(item=>observer.observe(item));
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,prism=document.querySelector('.prism-wrap');if(!reduce)document.querySelector('.hero').addEventListener('pointermove',event=>{const x=(event.clientX/innerWidth-.5)*12,y=(event.clientY/innerHeight-.5)*12;prism.style.transform=`translateY(-50%) rotateY(${x}deg) rotateX(${-y}deg)`});
addEventListener('scroll',()=>document.querySelector('.header').classList.toggle('scrolled',scrollY>20),{passive:true});
const reviews=[['После консультации впервые появилась ясность: что происходит, что делать дальше и почему. Очень ценю спокойный разговор без лишних назначений.','Алексей, пациент клиники','Кардиология · 2026'],['Врач не торопила, внимательно собрала историю и объяснила каждое назначение. Именно такого отношения я ждала от современной клиники.','Мария, пациентка клиники','Терапия · 2026'],['Пришли с ребёнком по рекомендации. Получили понятный план и ответы на все вопросы — без тревоги и ненужных обследований.','Елена, мама пациента','Педиатрия · 2026']];document.querySelectorAll('.review-dots button').forEach((dot,index)=>dot.addEventListener('click',()=>{document.querySelector('.review-dots .active').classList.remove('active');dot.classList.add('active');const stage=document.querySelector('.review-stage');stage.animate([{opacity:.2,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:500});stage.querySelector('blockquote').textContent=reviews[index][0];const spans=stage.querySelectorAll('.review-meta span');spans[0].textContent=reviews[index][1];spans[1].textContent=reviews[index][2]}));
