const accessGate=document.querySelector('[data-access-gate]'),accessForm=document.querySelector('[data-access-form]'),accessError=document.querySelector('[data-access-error]');
function unlockPreview(){document.body.classList.remove('locked');accessGate.classList.add('is-leaving');setTimeout(()=>{accessGate.hidden=true},650)}
if(sessionStorage.getItem('ametist-preview-access')==='granted'){accessGate.hidden=true;document.body.classList.remove('locked')}else{accessForm.addEventListener('submit',event=>{event.preventDefault();const password=new FormData(accessForm).get('password');if(password==='9876'){sessionStorage.setItem('ametist-preview-access','granted');unlockPreview()}else{accessError.hidden=false;accessGate.classList.remove('shake');void accessGate.offsetWidth;accessGate.classList.add('shake');accessForm.elements.password.select()}})}
const doctors=[
['Бабин','Вячеслав Вячеславович','Терапевт, кардиолог, аритмолог','Кандидат медицинских наук','therapy','images/doctors/babin-vyacheslav.svg','babin'],
['Бабина','Ирина Александровна','Ревматолог, терапевт, врач УЗИ и функциональной диагностики','Высшая квалификационная категория','therapy','images/doctors/babina-irina.svg','babina'],
['Калинина','Екатерина Николаевна','Терапевт','Высшая квалификационная категория','therapy','images/doctors/kalinina-ekaterina.svg','kalinina'],
['Закройщикова','Инесса Владимировна','Невролог, специалист по демиелинизирующим заболеваниям ЦНС','Кандидат медицинских наук','neuro','images/doctors/zakroishchikova-inessa.svg','zakroishchikova'],
['Ганин','Дмитрий Алексеевич','Невролог','','neuro'],
['Свиридонова','Марина Александровна','Эндокринолог, диетолог','Кандидат медицинских наук','therapy','images/doctors/sviridonova-marina.svg','sviridonova'],
['Куренков','Андрей Владимирович','Педиатр','','children'],
['Харзиани','Елена Валерьевна','Клинический психолог','','psychology'],
['Мавлиева','Радмила Руслановна','Психолог','','psychology'],
['Кузнецов','Павел Андреевич','Акушер-гинеколог','Кандидат медицинских наук','women'],
['Голубкова','Наталья Сергеевна','Акушер-гинеколог, гинеколог-эндокринолог, врач УЗИ','','women'],
['Павличенко','Светлана Николаевна','Терапевт, кардиолог, клинический фармаколог, диетолог','Кандидат медицинских наук','therapy','images/doctors/pavlichenko-svetlana.svg','pavlichenko'],
['Кузина','Дарья Евгеньевна','Детский гастроэнтеролог','','children'],
['Исакова','Светлана Сергеевна','Терапевт, гастроэнтеролог','','therapy']
];
const grid=document.querySelector('[data-doctor-grid]'),more=document.querySelector('[data-doctor-more]');
function render(filter='all',expanded=false){const list=doctors.filter(d=>filter==='all'||d[4]===filter);grid.innerHTML=list.map((d,i)=>`<article class="doctor ${!expanded&&i>7?'hidden':''}"><div class="doctor-portrait">${d[5]?`<img src="${d[5]}" alt="${d[0]} ${d[1]}" loading="lazy" decoding="async">`:`<span class="doctor-initials">${d[0][0]}${d[1][0]}</span>`}</div><div class="doctor-info"><h3>${d[0]}<br>${d[1]}</h3><p>${d[2]}</p><small>${d[3]||'Специалист клиники «Аметист»'}</small><div class="doctor-info__actions">${d[6]?`<button class="js-profile" type="button" data-profile="${d[6]}">Подробнее</button>`:''}<button class="js-book" type="button">Записаться ↗</button></div></div></article>`).join('');more.hidden=list.length<=8;bindBooking();bindProfiles()}
render();
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');button.classList.add('active');render(button.dataset.filter)}));
more.addEventListener('click',()=>{document.querySelectorAll('.doctor.hidden').forEach(card=>card.classList.remove('hidden'));more.hidden=true});
const menuButton=document.querySelector('.menu-btn'),menu=document.querySelector('#menu');menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));menu.classList.toggle('open')});menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
function profileSection(title,content){return `<section><h3>${title}</h3>${content}</section>`}
function openProfile(key){
 const data=doctorProfiles[key];if(!data)return;
 profile.querySelector('[data-profile-photo]').src=data.photo;profile.querySelector('[data-profile-photo]').alt=data.name;
 profile.querySelector('[data-profile-specialties]').textContent=data.specialties;profile.querySelector('[data-profile-name]').textContent=data.name;profile.querySelector('[data-profile-intro]').textContent=data.intro;
 const facts=[...data.facts,['Стоимость приёма','5 000 ₽'],['Онлайн-консультация','5 000 ₽']].map(([term,value])=>`<div><dt>${term}</dt><dd>${value}</dd></div>`).join('');
 const list=items=>`<ul class="doctor-profile__list">${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
 const paragraphs=items=>items.map(item=>`<p>${item}</p>`).join('');
 const education=`<ul class="doctor-profile__timeline">${data.education.map(([title,place])=>`<li><strong>${title}</strong><span>${place}</span></li>`).join('')}</ul>`;
 const faq=`<div class="doctor-profile__faq">${data.faq.map(([question,answer])=>`<details><summary>${question}</summary><p>${answer}</p></details>`).join('')}</div>`;
 profile.querySelector('[data-profile-body]').innerHTML=profileSection('Краткая информация',`<dl class="doctor-profile__facts">${facts}</dl>`)+profileSection('Профессиональная экспертиза',paragraphs(data.expertise))+`<blockquote class="doctor-profile__quote">«${data.quote}»</blockquote>`+profileSection('Специализация',list(data.specialization))+profileSection('С какими вопросами можно обратиться',list(data.reasons))+profileSection('Образование',education)+profileSection('Повышение квалификации',`<p>${data.training}</p>`)+profileSection('Опыт работы',`<p>${data.experience}</p>`)+(data.science?profileSection('Научная и профессиональная деятельность',`<p>${data.science}</p>`):'')+profileSection('Часто задаваемые вопросы',faq);
 profile.scrollTop=0;profile.showModal();
}
const modal=document.querySelector('.modal'),profile=document.querySelector('[data-doctor-profile]');function bindBooking(){document.querySelectorAll('.js-book').forEach(button=>button.onclick=()=>modal.showModal())}function bindProfiles(){document.querySelectorAll('.js-profile').forEach(button=>button.onclick=()=>openProfile(button.dataset.profile))}bindBooking();bindProfiles();document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});document.querySelector('[data-profile-close]').addEventListener('click',()=>profile.close());profile.addEventListener('click',event=>{if(event.target===profile)profile.close()});document.querySelector('.js-profile-book').addEventListener('click',()=>{profile.close();modal.showModal()});modal.querySelector('form').addEventListener('submit',event=>{event.preventDefault();event.currentTarget.hidden=true;modal.querySelector('.success').hidden=false});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(item=>observer.observe(item));
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,prism=document.querySelector('.prism-wrap');if(!reduce)document.querySelector('.hero').addEventListener('pointermove',event=>{const x=(event.clientX/innerWidth-.5)*12,y=(event.clientY/innerHeight-.5)*12;prism.style.transform=`translateY(-50%) rotateY(${x}deg) rotateX(${-y}deg)`});
addEventListener('scroll',()=>document.querySelector('.header').classList.toggle('scrolled',scrollY>20),{passive:true});
const reviews=[['После консультации впервые появилась ясность: что происходит, что делать дальше и почему. Очень ценю спокойный разговор без лишних назначений.','Алексей, пациент клиники','Кардиология · 2026'],['Врач не торопила, внимательно собрала историю и объяснила каждое назначение. Именно такого отношения я ждала от современной клиники.','Мария, пациентка клиники','Терапия · 2026'],['Пришли с ребёнком по рекомендации. Получили понятный план и ответы на все вопросы — без тревоги и ненужных обследований.','Елена, мама пациента','Педиатрия · 2026']];document.querySelectorAll('.review-dots button').forEach((dot,index)=>dot.addEventListener('click',()=>{document.querySelector('.review-dots .active').classList.remove('active');dot.classList.add('active');const stage=document.querySelector('.review-stage');stage.animate([{opacity:.2,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:500});stage.querySelector('blockquote').textContent=reviews[index][0];const spans=stage.querySelectorAll('.review-meta span');spans[0].textContent=reviews[index][1];spans[1].textContent=reviews[index][2]}));
