const accessGate=document.querySelector('[data-access-gate]'),accessForm=document.querySelector('[data-access-form]'),accessError=document.querySelector('[data-access-error]');
function unlockPreview(){document.body.classList.remove('locked');accessGate.classList.add('is-leaving');setTimeout(()=>{accessGate.hidden=true},650)}
if(sessionStorage.getItem('ametist-preview-access')==='granted'){accessGate.hidden=true;document.body.classList.remove('locked')}else{accessForm.addEventListener('submit',event=>{event.preventDefault();const password=new FormData(accessForm).get('password');if(password==='9876'){sessionStorage.setItem('ametist-preview-access','granted');unlockPreview()}else{accessError.hidden=false;accessGate.classList.remove('shake');void accessGate.offsetWidth;accessGate.classList.add('shake');accessForm.elements.password.select()}})}
const doctors=[
['Бабин','Вячеслав Вячеславович','Терапевт, кардиолог, аритмолог','Кандидат медицинских наук','therapy cardiology','images/doctors/babin-vyacheslav.svg','babin'],
['Бабина','Ирина Александровна','Ревматолог, терапевт, врач УЗИ и функциональной диагностики','Высшая квалификационная категория','therapy rheumatology diagnostics','images/doctors/babina-irina.svg','babina'],
['Калинина','Екатерина Николаевна','Терапевт','Высшая квалификационная категория','therapy','images/doctors/kalinina-ekaterina.svg','kalinina'],
['Закройщикова','Инесса Владимировна','Невролог, специалист по демиелинизирующим заболеваниям ЦНС','Кандидат медицинских наук','neurology','images/doctors/zakroishchikova-inessa.svg','zakroishchikova'],
['Ганин','Дмитрий Алексеевич','Невролог','','neurology'],
['Свиридонова','Марина Александровна','Эндокринолог, диетолог','Кандидат медицинских наук','endocrinology dietology','images/doctors/sviridonova-marina.svg','sviridonova'],
['Куренков','Андрей Владимирович','Педиатр','','children'],
['Харзиани','Елена Валерьевна','Клинический психолог','','psychology'],
['Мавлиева','Радмила Руслановна','Психолог','','psychology'],
['Кузнецов','Павел Андреевич','Акушер-гинеколог','Кандидат медицинских наук','women'],
['Голубкова','Наталья Сергеевна','Акушер-гинеколог, гинеколог-эндокринолог, врач УЗИ','','women'],
['Павличенко','Светлана Николаевна','Терапевт, кардиолог, клинический фармаколог, диетолог','Кандидат медицинских наук','therapy cardiology dietology','images/doctors/pavlichenko-svetlana.svg','pavlichenko'],
['Кузина','Дарья Евгеньевна','Детский гастроэнтеролог','','children'],
['Исакова','Светлана Сергеевна','Терапевт, гастроэнтеролог','','therapy']
];
const grid=document.querySelector('[data-doctor-grid]'),more=document.querySelector('[data-doctor-more]');
function doctorPage(doctor){return doctor[6]?doctorProfiles[doctor[6]].page:''}
function portraitMarkup(doctor){
 const fallback=doctor[5];
 if(!fallback)return `<span class="doctor-initials">${doctor[0][0]}${doctor[1][0]}</span>`;
 const image=`<img src="${fallback}" data-photo-fallback="${fallback}" alt="${doctor[0]} ${doctor[1]}" loading="lazy" decoding="async">`;
 return doctor[6]?`<a class="doctor-photo" href="${doctorPage(doctor)}" aria-label="Открыть страницу врача ${doctor[0]} ${doctor[1]}">${image}</a>`:image;
}
function render(filter='all',expanded=false){
 const list=doctors.filter(doctor=>filter==='all'||doctor[4].split(' ').includes(filter));
 grid.innerHTML=list.map((doctor,index)=>`<article class="doctor ${!expanded&&index>7?'hidden':''}"><div class="doctor-portrait">${portraitMarkup(doctor)}</div><div class="doctor-info"><h3>${doctor[6]?`<a class="doctor-name" href="${doctorPage(doctor)}">${doctor[0]}<br>${doctor[1]}</a>`:`${doctor[0]}<br>${doctor[1]}`}</h3><p>${doctor[2]}</p><small>${doctor[3]||'Специалист клиники «Аметист»'}</small><div class="doctor-info__actions">${doctor[6]?`<a href="${doctorPage(doctor)}">Подробнее о враче</a>`:''}<button class="js-book" type="button">Записаться ↗</button></div></div></article>`).join('');
 more.hidden=list.length<=8;activatePreferredPhotos(grid);bindBooking();
}
function activatePreferredPhotos(scope=document){scope.querySelectorAll('img[data-photo-fallback]').forEach(img=>{const png=img.dataset.photoFallback.replace(/\.svg$/i,'.png');const probe=new Image();probe.onload=()=>{img.src=png};probe.src=png})}
render();
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');button.classList.add('active');render(button.dataset.filter)}));
more.addEventListener('click',()=>{document.querySelectorAll('.doctor.hidden').forEach(card=>card.classList.remove('hidden'));more.hidden=true});
const menuButton=document.querySelector('.menu-btn'),menu=document.querySelector('#menu');menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));menu.classList.toggle('open')});menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const modal=document.querySelector('.modal');function bindBooking(){document.querySelectorAll('.js-book').forEach(button=>button.onclick=()=>modal.showModal())}bindBooking();document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});modal.querySelector('form').addEventListener('submit',event=>{event.preventDefault();event.currentTarget.hidden=true;modal.querySelector('.success').hidden=false});
const specialtyInfo={cardiology:['Кардиология','Диагностика, лечение и профилактика сердечно-сосудистых заболеваний: от контроля артериального давления и липидного обмена до нарушений ритма и сложных сочетанных состояний.'],therapy:['Терапия','Первичная оценка состояния, помощь при острых и хронических заболеваниях, профилактические осмотры и координация лечения, когда требуется несколько специалистов.'],rheumatology:['Ревматология','Диагностика и лечение заболеваний суставов, соединительной ткани, системных аутоиммунных заболеваний и хронических болевых синдромов.'],diagnostics:['УЗИ и функциональная диагностика','Ультразвуковые и функциональные исследования для взрослых и детей. Врач соотносит результаты исследования с клинической картиной и задачей лечащего специалиста.'],neurology:['Неврология','Помощь при головной боли, заболеваниях центральной и периферической нервной системы, демиелинизирующих и других сложных неврологических состояниях.'],endocrinology:['Эндокринология','Диагностика и лечение заболеваний щитовидной железы, нарушений углеводного и минерального обмена, остеопороза и других эндокринных состояний.'],dietology:['Диетология','Лечебное и профилактическое питание с учётом диагноза, образа жизни и принимаемой терапии — без необоснованных запретов и универсальных диет.']};
const specialtyDialog=document.querySelector('[data-specialty-dialog]');let selectedSpecialty='all';document.querySelectorAll('[data-specialty]').forEach(button=>button.addEventListener('click',()=>{selectedSpecialty=button.dataset.specialty;const [title,text]=specialtyInfo[selectedSpecialty];specialtyDialog.querySelector('[data-specialty-title]').textContent=title;specialtyDialog.querySelector('[data-specialty-text]').textContent=text;specialtyDialog.showModal()}));document.querySelector('[data-specialty-close]').addEventListener('click',()=>specialtyDialog.close());specialtyDialog.addEventListener('click',event=>{if(event.target===specialtyDialog)specialtyDialog.close()});document.querySelector('.js-specialty-doctors').addEventListener('click',()=>{specialtyDialog.close();const filter=document.querySelector(`.filters [data-filter="${selectedSpecialty}"]`);if(filter)filter.click();document.querySelector('#doctors').scrollIntoView({behavior:'smooth'})});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(item=>observer.observe(item));
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,prism=document.querySelector('.prism-wrap');if(!reduce)document.querySelector('.hero').addEventListener('pointermove',event=>{const x=(event.clientX/innerWidth-.5)*12,y=(event.clientY/innerHeight-.5)*12;prism.style.transform=`translateY(-50%) rotateY(${x}deg) rotateX(${-y}deg)`});
addEventListener('scroll',()=>document.querySelector('.header').classList.toggle('scrolled',scrollY>20),{passive:true});
const reviews=[['После консультации впервые появилась ясность: что происходит, что делать дальше и почему. Очень ценю спокойный разговор без лишних назначений.','Алексей, пациент клиники','Кардиология · 2026'],['Врач не торопила, внимательно собрала историю и объяснила каждое назначение. Именно такого отношения я ждала от современной клиники.','Мария, пациентка клиники','Терапия · 2026'],['Пришли с ребёнком по рекомендации. Получили понятный план и ответы на все вопросы — без тревоги и ненужных обследований.','Елена, мама пациента','Педиатрия · 2026']];document.querySelectorAll('.review-dots button').forEach((dot,index)=>dot.addEventListener('click',()=>{document.querySelector('.review-dots .active').classList.remove('active');dot.classList.add('active');const stage=document.querySelector('.review-stage');stage.animate([{opacity:.2,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:500});stage.querySelector('blockquote').textContent=reviews[index][0];const spans=stage.querySelectorAll('.review-meta span');spans[0].textContent=reviews[index][1];spans[1].textContent=reviews[index][2]}));
